# Generated by Django 6.1.1 on 2026-10-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(max_length=30, unique=True, verbose_name='รหัสการจอง')),
                ('student_id', models.CharField(max_length=20, verbose_name='รหัสนักศึกษา / เบอร์โทร')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวนที่จอง')),
                ('status', models.CharField(choices=[('reserved', 'จองแล้ว (Reserved)'), ('picked_up', 'รับสินค้าแล้ว (Picked Up)'), ('expired', 'หมดอายุ (Expired)'), ('cancelled', 'ยกเลิก (Cancelled)')], default='reserved', max_length=30, verbose_name='สถานะการจอง')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่จอง')),
                ('expires_at', models.DateTimeField(verbose_name='เวลาหมดอายุ')),
                ('picked_up_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลารับสินค้า')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop.location', verbose_name='สถานที่รับสินค้า')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shop.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการจองสินค้า',
                'verbose_name_plural': 'รายการจองสินค้าทั้งหมด',
                'db_table': 'reservations',
                'ordering': ['-reserved_at'],
            },
        ),
    ]
