# Generated by Django 6.1.1 on 2026-10-01 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดหมวดหมู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้าทั้งหมด',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อจุดจำหน่าย')),
                ('building', models.CharField(blank=True, max_length=100, verbose_name='ชื่อ/เลขอาคาร')),
                ('floor', models.CharField(blank=True, max_length=30, verbose_name='ชั้น')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='ห้องหรือบริเวณ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดสถานที่')),
            ],
            options={
                'verbose_name': 'สถานที่จำหน่าย',
                'verbose_name_plural': 'สถานที่จำหน่ายทั้งหมด',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาสินค้า (บาท)')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name='URL รูปภาพสินค้า')),
                ('reservable', models.BooleanField(default=True, help_text='1 = รองรับการจอง, 0 = ไม่รองรับการจอง', verbose_name='สินค้ารองรับการจอง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มสินค้า')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้าทั้งหมด',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='จำนวนคงเหลือ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop.location', verbose_name='สถานที่จำหน่าย')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='shop.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'สต็อกสินค้าตามสถานที่',
                'verbose_name_plural': 'สต็อกสินค้าตามสถานที่ทั้งหมด',
                'db_table': 'product_locations',
                'ordering': ['location', 'product'],
                'unique_together': {('product', 'location')},
            },
        ),
    ]
